import {
  Award,
  BookOpenText,
  CalendarCheck,
  CircleCheckBig,
  Compass,
  FolderOpen,
  Hammer,
  SquareKanban,
  Laptop,
  Layers,
  Lightbulb,
  MessageCircleHeart,
  MessagesSquare,
  MonitorSmartphone,
  Presentation,
  Route,
  Scale,
  Shapes,
  Sparkles,
  Target,
  UsersRound,
  UserRoundCheck,
  Workflow,
  House,
  ShieldCheck,
  LibraryBig,
  Rotate3d,
  BookImage,
  Sprout,
  Triangle,
  Bot,
  type LucideIcon,
} from "lucide-react";
import type { IconKey } from "../data/course";

const map: Record<IconKey, LucideIcon> = {
  compass: Compass,
  users: UsersRound,
  route: Route,
  kanban: SquareKanban,
  message: MessageCircleHeart,
  scale: Scale,
  laptop: Laptop,
  presentation: Presentation,
  hammer: Hammer,
  userSmall: UserRoundCheck,
  monitor: MonitorSmartphone,
  books: BookOpenText,
  messages: MessagesSquare,
  award: Award,
  lightbulb: Lightbulb,
  layers: Layers,
  workflow: Workflow,
  target: Target,
  sparkles: Sparkles,
  shapes: Shapes,
  calendar: CalendarCheck,
  check: CircleCheckBig,
  folder: FolderOpen,
  home: House,
  shield: ShieldCheck,
  library: LibraryBig,
  view360: Rotate3d,
  bookImage: BookImage,
  sprout: Sprout,
  triangle: Triangle,
  bot: Bot,
};

export function Icon({ name, className }: { name: IconKey; className?: string }) {
  const C = map[name];
  return <C className={className} aria-hidden="true" strokeWidth={1.9} />;
}
